export const ADMIN_PERMISSIONS = [
  'blog.view',
  'blog.create',
  'blog.update',
  'blog.delete',
  'blog.category.view',
  'blog.category.create',
  'blog.category.update',
  'blog.category.delete',
  'blog.tag.view',
  'blog.tag.create',
  'blog.tag.update',
  'blog.tag.delete',
  'portfolio.view',
  'portfolio.create',
  'portfolio.update',
  'portfolio.delete',
  'worktype.view',
  'worktype.create',
  'worktype.update',
  'worktype.delete',
  'media.view',
  'media.create',
  'media.update',
  'media.delete',
  'contact.view',
  'contact.update',
  'contact.delete',
  'settings.view',
  'stats.view',
] as const;

export type AdminPermission = (typeof ADMIN_PERMISSIONS)[number];
